config/routes.rb
Rails.application.routes.draw do
  # Read
  get 'tasks', to: 'tasks#index'
  # Create
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  # Read specific one
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  # Update
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'task_edit'
  patch 'tasks/:id', to: 'tasks#update'
  # Delete
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel=“stylesheet” href=“https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css”>
    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit <%= @task.title %></h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

<i class="fas fa-undo-alt"></i>
<%= link_to 'Back to list', tasks_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <% task.completed ? icon = 'fas' : icon = 'far' %>
      <i class="<%= icon %> fa-list-alt"></i>
      <%= link_to task.title, task_path(task) %>
      <i class="far fa-trash-alt"><%= link_to 'Delete',
                                              task_path(task),
                                              method: :delete,
                                              data: { confirm: "Are you sure?"}  %></i>
    </li>
  <% end %>
</ul>

<div class="d-flex">
  <i class="far fa-calendar-check"></i>
  <p><%= link_to 'Add a new task', tasks_new_path %></p>
</div>

app/views/tasks/new.html.erb
<h1>Add new task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<i class="fas fa-undo-alt"></i>
<%= link_to 'Back to list', tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<%= link_to 'Edit the task', task_edit_path(@task) %>

<p><%= @task.details %></p>
<div class="completed d-flex">
  <% @task.completed ? icon = 'fas' : icon = 'far' %>
  <i class="<%= icon %> fa-list-alt"></i>
  <% @task.completed ? label = 'Completed!' : label = "Not yet completed" %>
  <p><%= label %></p>
</div>

<br>

<i class="fas fa-undo-alt"></i>
<%= link_to 'Back to list', tasks_path %>